add on-new-mail hook
calls a single script for many new emails

diff --git a/src/static/bin/mailsummary b/src/static/bin/mailsummary
--- a/src/static/bin/mailsummary
+++ b/src/static/bin/mailsummary
@@ -5,6 +5,25 @@ basedir="$(readlink -f "$(dirname "$0")/../")"
 source "$(readlink -f "$basedir/activate")"
 query="tag:unread and NOT tag:killed $(jq < "$basedir/mailbundle.json" -r '.search.queryAppend.Unread' )"
 
-notmuch search --output=summary "$query" | awk '{ print substr($0, index($0,$2)) }'
+outputWhat=summary
+while getopts 'o:' opt
+do
+    case "$opt" in
+        o)
+        outputWhat="$OPTARG"
+        ;;
+        \?)
+        exit 2
+        ;;
+        *)
+        echo "Parse error" >&2
+        exit 2
+        ;;
+    esac
+done
+shift $((OPTIND-1))
+
+
+notmuch search --output="$outputWhat" "$query" | awk '{ print substr($0, index($0,$2)) }'
 
 
