outbox: save on disk!

diff --git a/src/static/bin/outbox b/src/static/bin/outbox
--- a/src/static/bin/outbox
+++ b/src/static/bin/outbox
@@ -3,7 +3,7 @@
 
 set -eu
 
-outbox=/tmp/outbox/
+outbox="$MAIL_ENV/outbox/"
 while getopts 'd:' opt
 do
     case "$opt" in
@@ -11,6 +11,10 @@ do
         outbox=$OPTARG
         ;;
         \?)
+        exit 2
+        ;;
+        *)
+        echo "Parse error" >&2
         exit 2
         ;;
     esac
diff --git a/src/static/bin/outbox-dequeue b/src/static/bin/outbox-dequeue
--- a/src/static/bin/outbox-dequeue
+++ b/src/static/bin/outbox-dequeue
@@ -2,12 +2,16 @@
 
 set -eu
 
-outbox=/tmp/outbox/
+outbox="$MAIL_ENV/outbox/"
 while getopts 'd:' opt
 do
     case "$opt" in
         d)
         outbox=$OPTARG
+        ;;
+        *)
+        echo "Parse error" >&2
+        exit 2
         ;;
     esac
 done
